version: '3'
services:
  server:
    build: .
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgres://root:Root123@db:5432/Todo
      PORT: 5000
    depends_on:
      - db
    restart:
      on-failure
    container_name: api
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    container_name: db
volumes:
  db-data:
